name: Open Github Issues Action
run-name: "Open Github Issues @${{github.actor}}, Event: ${{github.event_name}}"
on: 
    pull_request:
    push:
        branches:
            - main
            - 'releases/*'
jobs:
    # Units test
    units-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - run: npm ci
            - run: npm test
    test-smoth:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: ./
              id: issue
              with:
                token: ${{secrets.GITHUB_TOKEN}}
                title: Test Issue
                body: Test issue body
                assignees: |
                    HPierre

            - run: |
                echo ${{ steps.issue.outputs.issue}}



